name: pet_alert
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.15.0
  cupertino_icons: ^1.0.8
  flutter_foreground_task: ^9.2.2
  flutter_local_notifications: ^21.0.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  hive_ce_generator: ^1.11.1
  provider: ^6.1.5+1
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Pet_alert_Logo.png
    - assets/images/Pet_alert_Banner.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/Pet_alert_Logo.png

  android: true
  ios: true

  android_12:
    image: assets/images/Pet_alert_Logo.png
    color: "#ffffff"

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/images/Pet_alert_Logo.png"

  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/Pet_alert_Logo.png"